version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: smart_campus_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: smart_campus
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_campus_app
    restart: always
    ports:
      - '5000:5000'
    environment:
      PORT: 5000
      DATABASE_URL: 'postgresql://postgres:postgrespassword@postgres:5432/smart_campus?schema=public'
      JWT_SECRET: 'production-super-secret-jwt-key-campus-2026'
      CORS_ORIGIN: 'http://localhost:5173'
    depends_on:
      - postgres

volumes:
  postgres_data:
